### ISSUE TITLE
pc says it has virus

### ISSUE THREAD

**Issue by MrEvil125** [maxnut/GDmenu#146] opened 2024-01-08 09:56 UTC
can anyone give suggestions to fix this?

**Comment by sokilopersonal** [comment] 2024-01-08 11:40
Disable your anti-malware.

**Comment by Stronkkey** [comment] 2024-01-08 13:15
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119. Just exclude from Window Defender.

**Closed as not planned** 2024-01-08 13:34 UTC
