### ISSUE TITLE
will not open with gd

### ISSUE THREAD

**Issue by OneCopperPipe** [maxnut/GDmenu#140] opened 2024-01-07 01:28 UTC
I have tried re-installing gd, the mods, etc, and they will not open with gd. not sure why, but im not too happy. the file -Macro- isn't in the GDMO file, so maybe thats why.

**Comment by OneCopperPipe** [comment] 2024-01-07 01:52
and its even worse now, windows defender is not letting me do ANYTHING with this, i tried deactivating windows defender but it straight up said "this file is too dangerous too keep".  dam it

**Comment by creeperita09** [comment] 2024-01-07 09:20
read this: https://github.com/maxnut/GDMegaOverlay/issues/141#issuecomment-1879996480
and this:
> GDMO may show up as malware to some antiviruses. This is because of the method it uses to patch Geometry Dash, which is similar to how some malware works. GDMO is entirely safe, and the source code is avaliable to read if you have any concern

**Comment by creeperita09** [comment] 2024-01-07 10:04
> but it straight up said "this file is too dangerous too keep". 

just click the three dots -> downloads -> keep

**Comment by MysticAx0lotl** [comment] 2024-01-31 15:00
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119

**Closed as not planned** 2024-01-31 15:00 UTC
