### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by xNyfPtx** [maxnut/GDmenu#161] opened 2024-01-10 11:24 UTC
I know y'all have the source code but is virustotal reliable? Is this really malware or is it just flagged as malware due to its nature of changing gd's code
https://www.virustotal.com/gui/file/492670d77da23ee26c6f64e081d62a66f2aaf12d0b5bbf551deca066814193f0/relations

**Comment by howhathe** [comment] 2024-01-10 16:43
Hello, it's false, bc yes - it changes memory in the game and almost all detections (except 1) are caused by [xinput9_1_0.dll](https://www.virustotal.com/gui/file/b8be1a241fde00955c62a93ff6b4d54b58cadb790f2cb7991137911f070a52de). But anyway, it's safe as there are no weird imports like SHELLAPI.dll or something stuff
But if you still have fear, you can safely download some other injector or the same System Informer, lol

**Comment by Stronkkey** [comment] 2024-01-10 20:11
Duplicate of https://github.com/maxnut/GDMegaOverlay/issues/119. Just exclude from Window Defender. (This is the third time I am posting this, please check for closed issues before submitting one).

**Closed as not planned** 2024-01-10 22:43 UTC
