### ISSUE TITLE
Geometry Dash crashes again

### ISSUE THREAD

**Issue by LouisYouTube** [maxnut/GDmenu#214] opened 2024-02-02 10:29 UTC
gd crashes when exiting a level that has been botted

**Comment by tadolikepineapple** [comment] 2024-02-02 16:26
me 2

**Comment by MysticAx0lotl** [comment] 2024-02-02 22:13
No one can help you if you don't submit a crashlog

**Comment by tadolikepineapple** [comment] 2024-02-03 07:03
2024-02-02T17:26:15+0100
Whoopsies! An unhandled exception has occured.
It appears that the crash occurred while executing code from the "maxnu.gd_mega_overlay" mod. Please submit this crash report to its developer (maxnu & SpaghettDev) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.12
Loader Commit: 9cb3cf1
Bindings Commit: a684cc0
Installed mods: 4
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll
Faulty Mod: maxnu.gd_mega_overlay
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 64428EE1 (maxnu.gd_mega_overlay.dll + b8ee1)
Number Parameters: 2

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + b8ee1
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + a93d4
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 63f68
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 551a8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + cecc5
 - 1A7D0CCB
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c6596 (gdMainHook + 406 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:58)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 17ba9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bd2b (RtlInitializeExceptionChain + 107)
 - C:\Windows\SYSTEM32\ntdll.dll + 6bcaf (RtlClearBits + 191)

== Register States ==
EAX: 00000000
EBX: 7fffffff
ECX: 647d9844
EDX: 74657263
EBP: 0117f5f4
ESP: 0117f330
EDI: 647c603c
ESI: 647d985c
EIP: 64428ee1

== Installed Mods ==
x | [v1.2.1] beat.click-sound
x | [v2.0.0-beta.12] geode.loader
x | [v2.3.0] maxnu.gd_mega_overlay
x | [v1.3.0] zilko.xdbot

**Comment by Stronkkey** [comment] 2024-02-05 16:11
Try disabling your other mods.

**Comment by maxnut** [comment] 2024-02-06 15:59
fixed in 8288ea0a658114c19380776b8fd72a1baa3d17c9, was caused by saving macro outside level

**Closed as completed by maxnut** 2024-02-06 15:59 UTC
